Traceback (most recent call last):
  File "C:\Users\Mark\AppData\Roaming\Python\Python310\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Mark\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Mark\AppData\Roaming\Python\Python310\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Mark\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Mark\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Mark\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
author = articles[0].find("div", class_="szerzo").text.strip()
date = articles[0].find("div", class_="datum")
published = date.contents[0].strip()
title = articles[0].find("a").get("title")
subtitle = articles[0].find("div", class_="ajanlo").text.strip()
url = articles[0].find("a").get("href")

print("SzerzÅ‘: " + author)
print("DÃ¡tum: " + published)
print("CÃ­m: " + title)
print("AlcÃ­m: " + subtitle)
print("url: " + url)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[7], line 1[0m
[1;32m----> 1[0m author [38;5;241m=[39m [43marticles[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;241;43m.[39;49m[43mfind[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mdiv[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mclass_[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mszerzo[39;49m[38;5;124;43m"[39;49m[43m)[49m[38;5;241;43m.[39;49m[43mtext[49m[38;5;241m.[39mstrip()
[0;32m      2[0m date [38;5;241m=[39m articles[[38;5;241m0[39m][38;5;241m.[39mfind([38;5;124m"[39m[38;5;124mdiv[39m[38;5;124m"[39m, class_[38;5;241m=[39m[38;5;124m"[39m[38;5;124mdatum[39m[38;5;124m"[39m)
[0;32m      3[0m published [38;5;241m=[39m date[38;5;241m.[39mcontents[[38;5;241m0[39m][38;5;241m.[39mstrip()

[1;31mAttributeError[0m: 'NoneType' object has no attribute 'text'

